# Generated by Django 3.0.8 on 2020-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivicConnect', '0003_auto_20201022_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
