# Generated by Django 3.0.8 on 2020-10-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CivicConnect', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
