# Generated by Django 3.0.8 on 2020-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivicConnect', '0007_templatesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesubmission',
            name='topic',
            field=models.CharField(default='Topic goes here', max_length=100),
        ),
    ]
