# Generated by Django 3.1.2 on 2020-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CivicConnect', '0008_auto_20201113_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesubmission',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
