# Generated by Django 3.1.2 on 2020-11-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CivicConnect', '0009_templatesubmission_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesubmission',
            name='associated_interests',
            field=models.ManyToManyField(default=[], to='CivicConnect.Interest'),
        ),
        migrations.AddField(
            model_name='templatesubmission',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CivicConnect.profile'),
        ),
        migrations.AddField(
            model_name='templatesubmission',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='templatesubmission',
            name='template',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='templatesubmission',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
